parameters:
    pool: ''
    machine: ''
    kernel: ''
    buildtype: ''

jobs:
- job: ${{ parameters.machine }}_${{ parameters.kernel }}
  pool: ${{ parameters.pool }}
  timeoutInMinutes: 0

  steps:
  - template: steps_setup.yml
    parameters:
      machine: ${{ parameters.machine }}
      kernel: ${{ parameters.kernel }}
      build_branch: $(Build.SourceBranchName)
  - template: steps_artifacts.yml
    parameters:
      buildtype: ${{ parameters.buildtype }}
  - template: steps_build.yml
    parameters:
      buildtype: ${{ parameters.buildtype }}
