trigger:
 - master
 - master-next
 - dunfell

schedules:
- cron: "0 7 * * *"
  displayName: Daily build
  branches:
    include:
    - master
    - dunfell
  always: true


variables:
  - template: templates/variables.yml

jobs:
  - template: templates/build.yml
    parameters:
      pool:
        vmImage: 'ubuntu-20.04'
      buildtype: 'chromebook'
      machine: 'eve'
      kernel: 'yocto'
      debugit: $(debugit)

