trigger: none

schedules:
- cron: "0 0 * * *"
  displayName: Daily build
  branches:
    include:
    - master
    - dunfell
  always: true

variables:
  - template: templates/variables.yml

jobs:
  - template: templates/build.yml
    parameters:
      pool:
        vmImage: 'ubuntu-20.04'
      buildtype: 'poky'
      machine: 'qemux8664'
      kernel: 'yocto'

  - template: templates/build.yml
    parameters:
      pool:
        vmImage: 'ubuntu-20.04'
      buildtype: 'poky'
      machine: 'mediatek8173'
      kernel: 'chromium'

  - template: templates/build.yml
    parameters:
      pool:
        vmImage: 'ubuntu-20.04'
      buildtype: 'poky'
      machine: 'eve'
      kernel: 'yocto'

  - template: templates/build.yml
    parameters:
      pool:
        vmImage: 'ubuntu-20.04'
      buildtype: 'poky'
      machine: 'x86'
      kernel: 'intel'