trigger:
 - master
 - master-next
 - zeus

schedules:
- cron: "0 9 * * *"
  displayName: Daily build
  branches:
    include:
    - master
    - zeus
  always: true


variables:
  - template: templates/variables.yml

jobs:
  - template: templates/build.yml
    parameters:
      pool:
        vmImage: 'ubuntu-18.04'
      buildtype: 'chromebook'
      machine: 'mediatek-8173'
      kernel: 'chromium'

