trigger: none

schedules:
- cron: "0 6 * * *"
  displayName: Daily build
  branches:
    include:
    - master
    - zeus
  always: true

variables:
  - template: templates/variables.yml

jobs:
- job: SstateJob
  timeoutInMinutes: 0

  pool:
    vmImage: 'ubuntu-18.04'

  steps:
  - checkout: none

  - bash: |
      if [ $(Build.SourceBranchName) == "zeus" ]; then
        echo "##vso[task.setvariable variable=buildbranch;]refs/heads/zeus"
      else
        echo "##vso[task.setvariable variable=buildbranch;]refs/heads/master"
      fi
    displayName: 'Configure build'

  - bash: |
      sudo mkdir $(SSTATE_DIR)
      sudo mkdir $(DEPLOY_ARTIFACTS_DIR)
      sudo chown vsts:vsts $(SSTATE_DIR)
      sudo chown vsts:vsts ${DEPLOY_ARTIFACTS_DIR}
      echo "${BUILDBRANCH}"
      echo $(PIPELINE_EVE_YOCTO)
    displayName: 'Set up container directories'


################## SState EVE ##################
  - task: DownloadPipelineArtifact@2
    condition: always()
    inputs:
      source: 'specific'
      project: $(System.TeamProjectId)
      pipeline: $(PIPELINE_EVE_YOCTO)
      runVersion: 'latestFromBranch'
      runBranch: $(BUILDBRANCH)
      artifactName: 'SState'
      targetPath: $(SSTATE_DIR)

  - task: DownloadPipelineArtifact@2
    condition: always()
    inputs:
      source: 'specific'
      project: $(System.TeamProjectId)
      pipeline: $(PIPELINE_EVE_INTEL)
      runVersion: 'latestFromBranch'
      runBranch: $(BUILDBRANCH)
      artifactName: 'SState'
      targetPath: $(SSTATE_DIR)

  - task: DownloadPipelineArtifact@2
    condition: always()
    inputs:
      source: 'specific'
      project: $(System.TeamProjectId)
      pipeline: $(PIPELINE_EVE_CHROMIUM)
      runVersion: 'latestFromBranch'
      runBranch: $(BUILDBRANCH)
      artifactName: 'SState'
      targetPath: $(SSTATE_DIR)


################## SState x86 ##################
  - task: DownloadPipelineArtifact@2
    condition: always()
    inputs:
      source: 'specific'
      project: $(System.TeamProjectId)
      pipeline: $(PIPELINE_X86_YOCTO)
      runVersion: 'latestFromBranch'
      runBranch: $(BUILDBRANCH)
      artifactName: 'SState'
      targetPath: $(SSTATE_DIR)

  - task: DownloadPipelineArtifact@2
    condition: always()
    inputs:
      source: 'specific'
      project: $(System.TeamProjectId)
      pipeline: $(PIPELINE_X86_INTEL)
      runVersion: 'latestFromBranch'
      runBranch: $(BUILDBRANCH)
      artifactName: 'SState'
      targetPath: $(SSTATE_DIR)

  - task: DownloadPipelineArtifact@2
    condition: always()
    inputs:
      source: 'specific'
      project: $(System.TeamProjectId)
      pipeline: $(PIPELINE_X86_CHROMIUM)
      runVersion: 'latestFromBranch'
      runBranch: $(BUILDBRANCH)
      artifactName: 'SState'
      targetPath: $(SSTATE_DIR)

  - publish: $(SSTATE_DIR)
    artifact: 'SState'
    condition: always()
