trigger: none

schedules:
- cron: "0 6 * * *"
  displayName: Daily build
  branches:
    include:
    - master
    - zeus
  always: true

variables:
  - template: templates/variables.yml

jobs:
  - template: templates/steps_sstate.yml
    parameters:
      pool:
        vmImage: 'ubuntu-18.04'
      buildtype: 'sstate'
      machine: 'eve'
  - template: templates/steps_sstate.yml
    parameters:
      pool:
        vmImage: 'ubuntu-18.04'
      buildtype: 'sstate'
      machine: 'x86'
  - template: templates/steps_sstate.yml
    parameters:
      pool:
        vmImage: 'ubuntu-18.04'
      buildtype: 'sstate'
      machine: 'mediatek8173'
